backend:
  name: git-gateway
  branch: main # Or whatever your default branch is

media_folder: "public/images" # Where to store new images
public_folder: "/images" # The public URL for images

collections:
  - name: "profile_settings"
    label: "Profile Settings"
    
    files: 
      - file: "src/data/profile.json" # The actual file path
        label: "Linktree Profile Data"
        name: "linktree_data"
        
        fields: 
          - { label: "Name", name: "name", widget: "string" }
          - { label: "Bio", name: "bio", widget: "string" }
          - { label: "Profile Image", name: "imageUrl", widget: "image" }
          
          - name: "links"
            label: "Links"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }